#!/bin/sh
PIDFILE="/var/run/ffmpeg-record.pid"

FILESYSTEM=/dev/mmcblk0p2 #filesystem to monitor
CAPACITY=90 # delete oldest if FS is over 90% of usage 
PIDFILE2="/var/run/freespace-watcher.pid"
STORAGE_HOME="/media/mmcblk0p2/data/storage"
  
status()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
    kill -0 "$pid" >/dev/null && echo "PID: $pid" || return 1
  fi
}

start()
{
  killall ffmpeg
  
  LOG=/dev/null
  echo "Starting FFMPEG record and watchers..."
  FFMPEG_HOME="/media/mmcblk0p2/data/test/ffmpeg"
  #unixdate=$(date +%s)
  #streamname="stream-${unixdate}"
  mkdir -p $STORAGE_HOME
  cd $STORAGE_HOME
  $FFMPEG_HOME/ffmpeg -i rtsp://localhost/unicast -rtsp_transport tcp  -c copy -use_localtime 1 -hls_segment_filename 'camera1_%Y.%m.%d_%H.%M.%S.ts' -hls_time 10 -hls_list_size 0 $STORAGE_HOME/$streamname/stream.m3u8 >$LOG 2>&1 &
  echo "$!" > "$PIDFILE"
  
  
}

stop()
{
  pid="$(cat "$PIDFILE" 2>/dev/null)"
  if [ "$pid" ]; then
     kill $pid ||  rm "$PIDFILE"
  fi
}

if [ $# -eq 0 ]; then
  start
else
  case $1 in start|stop|status)
    $1
    ;;
  esac
fi

